[common]
compressAnywhere = false
compressBlacklist = ["minecraft:sandstone", "minecraft:iron_trapdoor"]
[client]
hideButtons = false
rightClickCraftsStack = false
hideButtonTooltips = false
hideVanillaCraftingGuide = false
craftingTweaksMode = "DEFAULT"
disabledAddons = []
